### ISSUE TITLE
后端的问题

### ISSUE THREAD

**Issue by jidangen** [Asaki-M/login-register-simple-case#1]
输入信息后点击注册报了这样的错误：
Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:83)
xhr.js?b50d:178 POST http://127.0.0.1:10520/api/user/login net::ERR_CONNECTION_REFUSED

**Comment by Asaki-M** [comment]
后端代码的配置换成你自己的没有

**Comment by jidangen** [comment]
需要改哪些呀？(눈‸눈)

**Comment by BojunZhong** [comment]
我这个也无法正常
![f95519b9293c6d6c484f95d9d41e949](https://user-images.githubusercontent.com/102637083/176341844-c731c252-28f3-46b3-af35-a125731960a9.png)
运

**Comment by BojunZhong** [comment]
为什么？

**Comment by Asaki-M** [comment]
@BojunZhong 数据库连接不上，你要确保你的数据库是否存在以及表名是否存在且跟代码一致

**Comment by BojunZhong** [comment]
谢谢

**Comment by HAILONG477** [comment]
你后端后错误啊,err is not defined
